# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ValetStorage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ValetStorage
  pod 'Alamofire'
  pod 'SwiftKeychainWrapper'
  pod 'AnimatedTextInput', '~> 0.3.0'

  target 'ValetStorageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ValetStorageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
